services:
  server1:
    container_name: Inventory.API
    build:
      context: ..
      dockerfile: PharmaTrack/Inventory.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=inventory-db;Database=Inventory;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=your_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8081:80"
      - "8082:443"
    depends_on:
      - inventory-db 

  inventory-db:
    container_name: Inventory.db  
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"  # Replace with a strong password
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"  # Expose SQL Server port
    volumes:
      - inventory-db-data:/var/opt/mssql  # Persist SQL data between restarts

volumes:
  inventory-db-data: