services:
  inventory-api:
    container_name: Inventory.API
    build:
      context: ..
      dockerfile: PharmaTrack/Inventory.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=inventory-db;Database=Inventory;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SuperSecretP@ss
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    ports:
      - "9083:80"
      - "9084:443"
    depends_on:
      - inventory-db

  auth-api:
    container_name: Auth.API
    build:
      context: ..
      dockerfile: PharmaTrack/Auth.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=auth-db;Database=Auth;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SuperSecretP@ss
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    ports:
      - "9085:80"
      - "9086:443"
    depends_on:
      - auth-db

  schedule-api:
    container_name: Schedule.API
    build:
      context: ..
      dockerfile: PharmaTrack/Schedule.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=schedule-db;Database=Schedule;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SuperSecretP@ss
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    ports:
      - "9087:80"
      - "9088:443"
    depends_on:
      - schedule-db

  drug-api:
    container_name: Drug.API
    build:
      context: ..
      dockerfile: PharmaTrack/Drug.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=drug-db;Database=Drug;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SuperSecretP@ss
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    ports:
      - "9089:80"
      - "9090:443"
    depends_on:
      - drug-db

  inventory-db:
    container_name: Inventory.db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - inventory-db-data:/var/opt/mssql

  auth-db:
    container_name: Auth.db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - auth-db-data:/var/opt/mssql

  schedule-db:
    container_name: Schedule.db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1435:1433"
    volumes:
      - schedule-db-data:/var/opt/mssql

  drug-db:
    container_name: Drug.db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1436:1433"
    volumes:
      - drug-db-data:/var/opt/mssql

volumes:
  inventory-db-data:
  auth-db-data:
  schedule-db-data:
  drug-db-data: