services:
  gateway-api:
    container_name: Gateway.API
    build:
      context: ..
      dockerfile: PharmaTrack/Gateway.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AuthApi__BaseUrl=http://auth-api
      - InventoryApi__BaseUrl=http://inventory-api
      - ScheduleApi__BaseUrl=http://schedule-api
      - DrugApi__BaseUrl=http://drug-api 
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=your_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8081:80"
      - "8082:443"

  inventory-api:
    container_name: Inventory.API
    build:
      context: ..
      dockerfile: PharmaTrack/Inventory.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=inventory-db;Database=Inventory;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=your_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8083:80"
      - "8084:443"
    depends_on:
      - inventory-db

  auth-api:
    container_name: Auth.API
    build:
      context: ..
      dockerfile: PharmaTrack/Auth.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=auth-db;Database=Auth;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=your_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8085:80"
      - "8086:443"
    depends_on:
      - auth-db
 
  schedule-api:
    container_name: Schedule.API
    build:
      context: ..
      dockerfile: PharmaTrack/Schedule.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=schedule-db;Database=Schedule;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=your_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8087:80"
      - "8088:443"
    depends_on:
      - schedule-db

  drug-api:
    container_name: Drug.API
    build:
      context: ..
      dockerfile: PharmaTrack/Drug.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=drug-db;Database=Drug;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=your_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8089:80"
      - "8090:443"
    depends_on:
      - drug-db

  inventory-db:
    container_name: Inventory.db  
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"  # Replace with a strong password
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"  # Expose SQL Server port
    volumes:
      - inventory-db-data:/var/opt/mssql  # Persist SQL data between restarts
 
  auth-db:
    container_name: Auth.db  
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"  # Replace with a strong password
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"  # Expose SQL Server port
    volumes:
      - auth-db-data:/var/opt/mssql  # Persist SQL data between restarts
 
  schedule-db:
    container_name: Schedule.db  
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"  # Replace with a strong password
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1435:1433"  # Expose SQL Server port
    volumes:
      - schedule-db-data:/var/opt/mssql  # Persist SQL data between restarts
 
  drug-db:
    container_name: Drug.db  
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"  # Replace with a strong password
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1436:1433"  # Expose SQL Server port
    volumes:
      - drug-db-data:/var/opt/mssql  # Persist SQL data between restarts

volumes:
  inventory-db-data:
  auth-db-data:
  schedule-db-data:
  drug-db-data: