// <auto-generated />
using System;
using Drug.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drug.API.Migrations
{
    [DbContext(typeof(DrugDBContext))]
    [Migration("20250425175147_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmaTrack.Shared.DBModels.DrugCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressBillingFlag")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADDRESS_BILLING_FLAG");

                    b.Property<string>("AddressMailingFlag")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADDRESS_MAILING_FLAG");

                    b.Property<string>("AddressNotificationFlag")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADDRESS_NOTIFICATION_FLAG");

                    b.Property<string>("AddressOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADDRESS_OTHER");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CITY_NAME");

                    b.Property<int>("CompanyCode")
                        .HasColumnType("int")
                        .HasColumnName("COMPANY_CODE");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COMPANY_NAME");

                    b.Property<string>("CompanyType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COMPANY_TYPE");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COUNTRY");

                    b.Property<int>("DrugCode")
                        .HasColumnType("int")
                        .HasColumnName("DRUG_CODE");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASH");

                    b.Property<string>("MfrCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MFR_CODE");

                    b.Property<string>("PostOfficeBox")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("POST_OFFICE_BOX");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("POSTAL_CODE");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PROVINCE");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STREET_NAME");

                    b.Property<string>("SuiteNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUITE_NUMBER");

                    b.HasKey("Id");

                    b.ToTable("DrugCompanies");
                });

            modelBuilder.Entity("PharmaTrack.Shared.DBModels.DrugForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrugCode")
                        .HasColumnType("int")
                        .HasColumnName("DRUG_CODE");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASH");

                    b.Property<int>("PharmFormCode")
                        .HasColumnType("int")
                        .HasColumnName("PHARM_FORM_CODE");

                    b.Property<string>("PharmaceuticalForm")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PHARMACEUTICAL_FORM");

                    b.HasKey("Id");

                    b.ToTable("DrugForms");
                });

            modelBuilder.Entity("PharmaTrack.Shared.DBModels.DrugIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveIngredientCode")
                        .HasColumnType("int")
                        .HasColumnName("ACTIVE_INGREDIENT_CODE");

                    b.Property<string>("Base")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BASE");

                    b.Property<string>("DosageUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOSAGE_UNIT");

                    b.Property<string>("DosageValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOSAGE_VALUE");

                    b.Property<int>("DrugCode")
                        .HasColumnType("int")
                        .HasColumnName("DRUG_CODE");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASH");

                    b.Property<string>("Ingredient")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("INGREDIENT");

                    b.Property<string>("IngredientSuppliedInd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("INGREDIENT_SUPPLIED_IND");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOTES");

                    b.Property<string>("Strength")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STRENGTH");

                    b.Property<string>("StrengthType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STRENGTH_TYPE");

                    b.Property<string>("StrengthUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STRENGTH_UNIT");

                    b.HasKey("Id");

                    b.ToTable("DrugIngredients");
                });

            modelBuilder.Entity("PharmaTrack.Shared.DBModels.DrugInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugA")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Drug_A");

                    b.Property<string>("DrugAID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DDInterID_A");

                    b.Property<string>("DrugB")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Drug_B");

                    b.Property<string>("DrugBID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DDInterID_B");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASH");

                    b.Property<int>("InteractionID")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Level");

                    b.Property<string>("Management")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DrugInteractions");
                });

            modelBuilder.Entity("PharmaTrack.Shared.DBModels.DrugPackaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrugCode")
                        .HasColumnType("int")
                        .HasColumnName("DRUG_CODE");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASH");

                    b.Property<string>("PackageSize")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PACKAGE_SIZE");

                    b.Property<string>("PackageSizeUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PACKAGE_SIZE_UNIT");

                    b.Property<string>("PackageType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PACKAGE_TYPE");

                    b.Property<string>("ProductInformation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PRODUCT_INFORMATION");

                    b.Property<string>("Upc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPC");

                    b.HasKey("Id");

                    b.ToTable("DrugPackagings");
                });

            modelBuilder.Entity("PharmaTrack.Shared.DBModels.DrugPharmaceuticalStd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrugCode")
                        .HasColumnType("int")
                        .HasColumnName("DRUG_CODE");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASH");

                    b.Property<string>("PharmaceuticalStd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PHARMACEUTICAL_STD");

                    b.HasKey("Id");

                    b.ToTable("DrugPharmaceuticalStds");
                });

            modelBuilder.Entity("PharmaTrack.Shared.DBModels.DrugProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessionNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCESSION_NUMBER");

                    b.Property<string>("AiGroupNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AI_GROUP_NO");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BRAND_NAME");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLASS");

                    b.Property<string>("Descriptor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTOR");

                    b.Property<int>("DrugCode")
                        .HasColumnType("int")
                        .HasColumnName("DRUG_CODE");

                    b.Property<string>("DrugIdentificationNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DRUG_IDENTIFICATION_NUMBER");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASH");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LAST_UPDATE_DATE");

                    b.Property<string>("NumberOfAis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NUMBER_OF_AIS");

                    b.Property<string>("PediatricFlag")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PEDIATRIC_FLAG");

                    b.Property<string>("ProductCategorization")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PRODUCT_CATEGORIZATION");

                    b.HasKey("Id");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("PharmaTrack.Shared.DBModels.DrugRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrugCode")
                        .HasColumnType("int")
                        .HasColumnName("DRUG_CODE");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASH");

                    b.Property<string>("RouteOfAdministration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROUTE_OF_ADMINISTRATION");

                    b.Property<int>("RouteOfAdministrationCode")
                        .HasColumnType("int")
                        .HasColumnName("ROUTE_OF_ADMINISTRATION_CODE");

                    b.HasKey("Id");

                    b.ToTable("DrugRoutes");
                });

            modelBuilder.Entity("PharmaTrack.Shared.DBModels.DrugSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrugCode")
                        .HasColumnType("int")
                        .HasColumnName("DRUG_CODE");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASH");

                    b.Property<string>("Schedule")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SCHEDULE");

                    b.HasKey("Id");

                    b.ToTable("DrugSchedules");
                });

            modelBuilder.Entity("PharmaTrack.Shared.DBModels.DrugStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentStatusFlag")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CURRENT_STATUS_FLAG");

                    b.Property<int>("DrugCode")
                        .HasColumnType("int")
                        .HasColumnName("DRUG_CODE");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASH");

                    b.Property<DateTime?>("HistoryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("HISTORY_DATE");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("DrugStatuses");
                });

            modelBuilder.Entity("PharmaTrack.Shared.DBModels.DrugTherapeuticClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrugCode")
                        .HasColumnType("int")
                        .HasColumnName("DRUG_CODE");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASH");

                    b.Property<string>("TcAhfs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TC_AHFS");

                    b.Property<string>("TcAhfsNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TC_AHFS_NUMBER");

                    b.Property<string>("TcAtc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TC_ATC");

                    b.Property<string>("TcAtcNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TC_ATC_NUMBER");

                    b.HasKey("Id");

                    b.ToTable("DrugTherapeuticClasses");
                });

            modelBuilder.Entity("PharmaTrack.Shared.DBModels.DrugVeterinarySpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrugCode")
                        .HasColumnType("int")
                        .HasColumnName("DRUG_CODE");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASH");

                    b.Property<string>("VetSpecies")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VET_SPECIES");

                    b.Property<string>("VetSubSpecies")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VET_SUB_SPECIES");

                    b.HasKey("Id");

                    b.ToTable("DrugVeterinarySpecies");
                });
#pragma warning restore 612, 618
        }
    }
}
